package aksstoredemo:rules;

interface types {
    record product {
        id: s32,
        name: string,
        brand: string,
        price: float32,
        description: string,
        category: string,
        sku: string,
        quantity-available: s32,
        image-url: string,
        rating: float32,
        specifications: string,
    }
    
    variant error {
        invalid-product(string),
        pricing-standards-violation(string),
        engine-internal-error(string),
    }
}

interface logging {
    resource logger {
        constructor();
        log: func(msg: string);
    }
    
    get-logger: func() -> logger;
}

world service-host {
    import logging;
    export types;
    
    export rules-engine: interface {
        use types.{product, error};
        execute: func(p: product) -> result<product, error>;
    }
}